[package]
name = "hide"
authors = ["treize <darktreize@hotmail.fr>"]
version = "0.2.0"
edition = "2021"
description = "Hide your files"

[dependencies]
openssl = "0.10"
rpassword = "7.3"
rand = "0.8"
clap = "4.5"
zeroize = "1.8.1"

[profile.release]
lto = true
